name: Run tests and deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
     - uses: actions/checkout@v3
     - name: Use Node.js 17.x
       uses: actions/setup-node@v3
       with:
         node-version: 17.x
     - name: Install Node dependencies
       run: |
         cd server
         npm install
     - name: Run unit test suite
       env:
         MONGODB_URL: mongodb://mongo:27017/ecommerce
       run: |
         cd server
         npm test
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "backend2-ecommerce"
          heroku_email: "ekeroth.christoffer+test@gmail.com"
          appdir: "server"
